adobe/aio-cli-plugin-app

package-lock.json, package.json, src/commands/cna/deploy.js, src/commands/cna/undeploy.js
Update to latest cna scripts that use aio cli config
=> Update cna scripts

README.md, package-lock.json, package.json, src/CNABaseCommand.js, src/commands/cna/deploy.js, src/commands/cna/undeploy.js, test/CNABaseCommand.test.js
- [] My change requires a change to the documentation.
=> fixes for deploy cmd

src/templates/web-src/index.html, src/templates/web-src/src/index.js
Added sample HTML and JS to talk to hello action
- [] My change requires a change to the documentation.
=> add: sample ui template

src/templates/base/.gitignore, src/templates/base/package.json, src/templates/base/test/__setup__/jest.setup.js, src/templates/base/test/actions/actions.test.js
Add jest setup and single passing test to newly created projects.
=> Add template tests

src/commands/cna/init.js
Parse path for package name
Parsing the path to pick a valid package name that can work for an s3 folder
https://github.com/adobe/aio-cli-plugin-cna/issues/23
=> [ACNA-349] Parse path for package name

.gitignore, src/commands/cna/init.js, test/commands/cna/init.test.js
=> added bad-flag test, init command inherits base-command args

src/commands/cna/run.js
simple pr to show what's going on in run command
=> add info messages to run command

.github/workflows/nodejs.yml, test/commands/cna/init.test.js, test/commands/lib/cna-helper.test.js
=> fix failing async tests

package.json, src/templates/base/dotenv
changes in dotenv init template
=> change tvm url in init dotenv

README.md, jest.config.js, src/commands/cna/run.js, src/commands/cna/test.js, src/lib/cna-helper.js, test/commands/cna/run.test.js, test/commands/cna/test.test.js, test/commands/lib/cna-helper.test.js
`aio cna test`
Switching between aio and npm provides discrepancy in the end-to-end developer's experience.
=> Run test [ACNA-445]

README.md, jest.config.js, package.json, src/commands/cna/test.js, src/templates/base/README.md, test/commands/cna/test.test.js
=> ACNA - 455/456 - aio cna test > run unit and e2e tests

jest.config.js, src/commands/cna/test.js, src/lib/cna-helper.js, test/commands/cna/test.test.js, test/commands/lib/cna-helper.test.js
=> merge fix for test cmd

src/commands/cna/test.js, test/commands/cna/test.test.js
We had duplicate implementations, all cleaned up now.
=> cleanup implementation, test all flag combos

src/commands/cna/test.js, src/lib/cna-helper.js, test/commands/cna/test.test.js
=> Better test cmd error messages

package.json
=> fix deleted cna-scripts dep

src/commands/app/gen.js, src/generators/createGenerator.js
add -y | -yes so will choose the default answers, skip prompting questions
add -s will skip the install
=> add -y|-yes and -s flags

src/commands/app/gen.js, src/generators/createGenerator.js
FIrst arg is a path where the project should be created
=> add path arg to gen command

src/commands/app/init.js
=> added template flag and switching

src/templates/campaign/actions/README.md, src/templates/campaign/actions/campaign/campaignApi.js, src/templates/campaign/base/.aio, src/templates/campaign/base/.gitignore, src/templates/campaign/base/README.md, src/templates/campaign/base/_dot.env, src/templates/campaign/base/manifest.yml, src/templates/campaign/base/package.json, src/templates/campaign/base/test/__setup__/jest.setup.js, src/templates/campaign/base/test/actions/actions.test.js, src/templates/campaign/index.js, src/templates/campaign/web-src/README.md, src/templates/campaign/web-src/index.html, src/templates/campaign/web-src/src/index.js
=> Add Campaign Standard template (based off Target template)

src/generators/create-analytics.js, src/templates/analytics/actions/README.md, src/templates/analytics/actions/analytics/index.js, src/templates/analytics/base/.aio, src/templates/analytics/base/.gitignore, src/templates/analytics/base/README.md, src/templates/analytics/base/_dot.env, src/templates/analytics/base/manifest.yml, src/templates/analytics/base/package.json, src/templates/analytics/base/test/__setup__/jest.setup.js, src/templates/analytics/base/test/actions/actions.test.js, src/templates/analytics/index.js, src/templates/analytics/web-src/README.md, src/templates/analytics/web-src/index.html, src/templates/analytics/web-src/src/index.js
=> add basic analytics template support

src/generators/create-analytics.js, src/generators/create-hello.js, src/generators/create-target.js, src/templates/analytics/base/README.md, src/templates/campaign/base/README.md, src/templates/hello/base/README.md, src/templates/target/base/README.md
=> update user-messages with CNA text

src/commands/app/init.js, test/commands/app/init.test.js
If the user does not specify --yes and does not specify a template, we prompt for one.
=> prompt for template if none given

src/commands/app/run.js
=> better dev cmd error formatting

src/templates/campaign/actions/campaign/index.js, src/templates/campaign/base/package.json
Usage of core-logging.
Better examples.
deployed, and invoked.
=> Add logging to Campaign Standard template

.npmrc, README.md, package.json
Workaround is setting the `repositoryPrefix` in package.json oclif key.
Fix README links
=> fix: links in readme were showing the `v` prefix for version (which is hardcoded by oclif).

src/templates/analytics/actions/analytics/index.js, src/templates/analytics/base/README.md, src/templates/analytics/base/package.json, src/templates/campaign/base/README.md
- Add logging and error core SDK
- Add more comments to sample code
- Add more information in README
=> Better analytic template

src/generators/create-analytics.js, src/generators/create-campaign.js, src/generators/create-hello.js, src/generators/create-target.js, src/templates/analytics/base/package.json, src/templates/target/base/package.json
This fixes #97 
#97 
ran through all template init scripts and verified that package.json reflected my choice after init.
=> Respect user provided package name

README.md
=> Fix build badges (not found)

src/commands/app/add/action.js, src/commands/app/add/index.js, src/commands/app/add/web-assets.js, src/commands/app/delete/action.js, src/commands/app/delete/index.js, src/commands/app/delete/web-assets.js, test/commands/app/add/index.test.js, test/commands/app/delete/index.test.js
=> Fix app:add and app:delete help doc

package.json, src/commands/app/run.js, test/commands/app/run.test.js
- save the cert to config when we generate it
- ask the dev to accept it right away, using an quick and dirty server
- reuse it for new projects, it will not need to be accepted again
=> ACNA-640 run command changes

package.json, src/commands/app/deploy.js, src/commands/app/run.js, test/commands/app/deploy.test.js, test/commands/app/run.test.js
=> show exc and raw url for both run and deploy

README.md, package.json, src/commands/app/add/ci.js, src/commands/app/delete/ci.js, test/commands/app/add/ci.test.js, test/commands/app/delete/ci.test.js
need to bump the version of generator-io-app before merging this
=> CI using github actions

src/commands/app/undeploy.js, test/commands/app/undeploy.test.js
=> align undeploy flags with deploy command

src/commands/app/add/web-assets.js, test/commands/app/add/web-assets.test.js
=> fix service sdk codes on add web-assets

src/commands/app/init.js, test/commands/app/init.test.js
FYI @easingthemes 
relates to https://github.com/adobe/generator-aio-app/pull/30
=> Add AEP SDK code

src/commands/app/run.js
=> fix https option for new app scripts

jest.config.js, src/commands/app/deploy.js, src/commands/app/run.js, test/__mocks__/@adobe/aio-app-scripts.js, test/commands/app/deploy.test.js, test/commands/app/run.test.js, test/commands/app/undeploy.test.js
NB: this is a 2 in 1 pr
1. includes  #177 
2. fix for https://github.com/adobe/aio-cli-plugin-app/issues/163
- supports `aio app run --skip-actions`
- adds some checks in run:
- dont run if no web-src and no manifest
- dont run if no web-src and --skip-actions
=> coverage, refactor certificate generation and add support for run --skip-actions

src/BaseCommand.js, src/commands/app/deploy.js, src/commands/app/run.js, test/commands/app/deploy.test.js, test/commands/app/run.test.js
This displays a warning if the developer's .env contains an old format url /myapps/? ...
=> Warn on invalid launch_url_prefix

src/commands/app/init.js, test/commands/app/init.test.js
=> Add AM-CD code

src/BaseCommand.js, test/BaseCommand.test.js
update AIO_LAUNCH_URL_PREFIX to custom-apps
added tests to warn devs to update their env
=> update AIO_LAUNCH_URL_PREFIX to custom-apps

package.json, src/commands/app/use.js, src/lib/import.js, test/commands/app/use.test.js
Uses the new `generator-aio-console` release with ims-org-id, ims-project-id, ims-workspace-id options enhancement
npm test
aio app use (user interactive)
aio app use <config_file>
=> ACNA-735: `aio app use` enhancements

src/lib/import.js, test/__fixtures__/merge.1.final.env, test/__fixtures__/merge.1.new.env, test/__fixtures__/merge.1.old.env, test/__fixtures__/merge.2.final.env, test/__fixtures__/merge.2.new.env, test/__fixtures__/merge.2.old.env, test/commands/lib/import.test.js
=> fix: add mergeEnv, splitEnvLine tests

src/commands/app/init.js
Fixes #219
npm test
aio app init
aio app init projectpath
=> fix: app init fails when given path argument

package.json
=> chore(package): update eslint-plugin-jest to version 23.13.0

schema/config.schema.json, test/__fixtures__/existing.merged.aio, test/__fixtures__/valid.config.aio, test/__fixtures__/valid.config.json
Closes #230
IMS organization can be anything in Unicode BMP with a max of 255 characters.
The regex prevents leading or trailing whitespace characters.
Test on 5 chars max: https://regex101.com/r/IX4PYF/1
=> fix: overly restrictive organization pattern

.travis.yml
This works in Travis CI windows because the build is run under git-bash.
that's the purpose of this PR :)
=> Use codecov bash uploader

src/commands/app/add/action.js, src/commands/app/add/auth.js, src/commands/app/add/ci.js, src/commands/app/add/web-assets.js, src/commands/app/delete/action.js, src/commands/app/delete/ci.js, src/commands/app/delete/web-assets.js, src/commands/app/init.js, src/lib/app-helper.js, src/lib/import.js
=> use aioLogger and not debug() directly

src/commands/app/use.js, src/lib/import.js
=> fix: $console renamed to `console` (fixes #256)

src/commands/app/init.js, test/commands/app/init.test.js
This should not be committed until we are releasing the next version with asset-compute support in the generator.
adobe/generator-aio-app/pull/55
=> add asset-compute generator to the list

src/commands/app/delete/action.js, src/commands/app/delete/event.js, src/commands/app/delete/web-assets.js
=> fix delete message

src/commands/app/init.js, test/commands/app/init.test.js
=> remove feature flag `--asset-compute`

src/lib/config-loader.js, src/lib/defaults.js, src/lib/import.js, test/__fixtures__/existing.merged.env, test/__fixtures__/valid.config.env
Fixes https://github.com/adobe/aio-cli-plugin-app/issues/267
=> setting apihost to default

src/commands/app/add/action.js, test/commands/app/add/action.test.js
Fixes https://github.com/adobe/aio-cli-plugin-app/issues/288
=> Using services from imported config if present

package.json, src/lib/defaults.js
note this also bumps the aio-lib-web major: 4.0.0
=> change default tvm url

.eslintrc.json, test/commands/lib/ow-local.test.js, test/commands/lib/runDev.test.js, test/jest.setup.js
=> r => path.resolve, remove globals

src/commands/app/init.js, test/commands/app/init.test.js
=> Fix services error on --import

src/lib/runDev.js
Closes #277 
See steps in #277
=> fix: ACNA-885 - aio app run's auto-logger shows last action log for last activation even before the command was run

src/commands/app/run.js, src/lib/config-loader.js, src/lib/runDev.js, test/commands/app/run.test.js, test/commands/lib/poller.test.js, test/commands/lib/runDev.test.js
closes #326
npm test
aio app run --local --verbose
aio app run --verbose
=> fix: cannot deploy app to remote via `aio app run`, it's always local

src/lib/config-loader.js, test/commands/lib/config-loader.test.js
There is no `log` function in aio-lib-core-logging
nom test
- [] My change requires a change to the documentation.
=> fix: aioLogger.log undefined

src/commands/app/logs.js, test/commands/app/logs.test.js
https://github.com/adobe/aio-cli-plugin-app/issues/333
=> allow fetching logs from multiple actions

src/commands/app/build.js, src/commands/app/deploy.js, src/commands/app/undeploy.js, test/commands/app/build.test.js, test/commands/app/deploy.test.js, test/commands/app/undeploy.test.js
Fixes https://github.com/adobe/aio-cli-plugin-app/issues/312
=> adding skip-web-assets alias to skip-static

src/commands/app/run.js, src/lib/bundle-serve.js, src/lib/defaults.js, src/lib/run-dev.js, src/lib/serve.js, test/commands/app/run.test.js, test/commands/lib/bundle-serve.test.js, test/commands/lib/run-dev.test.js, test/commands/lib/serve.test.js
Fixes #369 
npm test
1. Create an app with React web assets
2. `aio app run --verbose`, wait until it shows you the urls to launch
3. Launch the displayed localhost url in a web browser
4. Edit any Sidebar text in `web-src/src/components/Sidebar.js` in your project, and save the changes
5. See the changes reflected in the Sidebar React component in the browser (browser should automatically reload)
=> fix: React template: cannot hot reload React components

.github/workflows/node.js.yml, schema/config.schema.json, test/__fixtures__/existing.merged.aio, test/__fixtures__/valid.config.aio, test/__fixtures__/valid.config.json
fix for https://github.com/adobe/aio-cli-plugin-app/issues/296
also needs https://github.com/adobe/generator-aio-console/pull/17
=> Update console config validation for project and workspace

package.json, src/lib/config-loader.js, src/lib/defaults.js, test/commands/lib/config-loader.test.js, test/commands/lib/run-dev.test.js
Setting proper hostname for stage S3 when env is set to "stage"
=> Stage env support

src/BaseCommand.js, test/BaseCommand.test.js
Also needs https://github.com/adobe/generator-aio-app/pull/137
=> Use experience stage url for stage env

package.json, test/__mocks__/@adobe/aio-lib-runtime.js, test/commands/app/build.test.js, test/commands/app/run.test.js, test/commands/lib/run-dev.test.js, test/jest.setup.js
=> Upgrade Jest for node14 support

src/lib/run-dev.js
=> removed unneeded @parcel/reporter-dev-server

package.json, src/lib/run-dev.js
Fixes https://github.com/adobe/aio-cli-plugin-app/issues/410
=> Enabling hmr for parcel

src/lib/app-helper.js
=> fix merge conflict

.github/workflows/release-branch.yml, package.json
Add a Github Action workflow to test pull requests against release-* branches.
TBD
=> add release branch ci

src/commands/app/init.js, src/lib/app-helper.js, src/lib/config-loader.js, test/BaseCommand.test.js, test/__fixtures__/app-exc-nui/src/dx-asset-compute-worker-1/ext.config.yaml, test/commands/app/init.test.js, test/commands/lib/config-loader.test.js, test/data-mocks/config-loader-include-index.js, test/data-mocks/config-loader.js
=> worker opcode change + tests BaseCommand & Init 

src/lib/cleanup.js, src/lib/vscode.js, test/commands/lib/build-actions.test.js, test/commands/lib/cleanup.test.js, test/commands/lib/deploy-actions.test.js, test/commands/lib/import.test.js, test/commands/lib/run-dev.test.js, test/commands/lib/run-local-runtime.test.js, test/commands/lib/vscode.test.js
The base branch is `release-ext-reg`
`npm test`, see that all the lib files pass and have 100% code cov
pending `aio app run` tests (local and remote)
=> fixed unit tests and coverage for lib files (Ext Reg support) 

test/commands/app/add/action.test.js, test/commands/app/add/ci.test.js, test/commands/app/add/event.test.js, test/commands/app/add/extension.test.js, test/commands/app/add/web-assets.test.js
=> Unit tests with 100% codecov for all app add cmds

src/lib/config-loader.js
=> remove deprecation notice for manifest

src/commands/app/deploy.js, src/commands/app/logs.js, src/commands/app/undeploy.js, test/commands/app/deploy.test.js, test/commands/app/undeploy.test.js
=> Fixes: app logs, deploy no-login legacy+app, no-build, no extra update extpoint call

src/commands/app/delete/action.js, src/commands/app/delete/extension.js, test/commands/app/delete/action.test.js, test/commands/app/delete/event.test.js, test/commands/app/delete/extension.test.js
=> Delete test coverage

src/commands/app/list/extension.js, src/lib/app-helper.js, src/lib/defaults.js, test/__fixtures__/app-exc-nui/src/dx-asset-compute-worker-1/ext.config.yaml, test/commands/app/deploy.test.js, test/commands/app/list/extension-points.test.js, test/commands/app/list/extension.test.js, test/commands/lib/app-helper.test.js, test/data-mocks/config-loader-include-index.js, test/data-mocks/config-loader.js
do not merge before ext registry change
https://github.com/adobe/generator-aio-app/pull/154
=> Rename NUI Operation

test/commands/app/add/web-assets.test.js, test/commands/app/delete/action.test.js, test/commands/lib/vscode.test.js
base branch is `release-ext-reg`
=> fix: failing unit tests on Windows

src/commands/app/delete/web-assets.js, src/commands/app/deploy.js, test/commands/app/delete/web-assets.test.js
=> grammar fixes

src/commands/app/deploy.js, test/commands/app/deploy.test.js
aio app deploy -a on an action that does not exist, shows a successful deploy
#443
=> Fix #443 - ACNA-1239

src/lib/cleanup.js, test/commands/lib/cleanup.test.js
Fixes https://github.com/adobe/aio-cli-plugin-app/issues/455
`aio app run` on Windows VM
=> fix: ctrl-c was not working properly for `aio app run` on windows

.github/workflows/on-push-publish-to-npm.yml, .github/workflows/version-bump-publish.yml, package.json
=> fix: @adobe/aio-lib-ims will require node-12 or greater starting July 14th, 2021

src/commands/app/deploy.js, src/commands/app/undeploy.js
=> nit: pass flag values instead of flags - least privilege

package.json
Consistent with https://github.com/adobe/generator-aio-app/pull/164 and https://github.com/adobe/generator-aio-console/pull/31
Fixes https://github.com/adobe/generator-aio-app/issues/134
=> Yeoman upgrade

src/commands/app/build.js, src/commands/app/deploy.js
adobe#470
@shazron brought it up
manually
```bash
🔥🐝 aio app deploy
build-actions
✖ build-action skipped by hook 'dx/excshell/1'
⠋ Building web assets
build-static
✖ build-static skipped by hook 'dx/excshell/1'
⠋ Deploying actions for 'dx/excshell/1'
deploy-actions
✖ deploy-actions skipped by hook 'dx/excshell/1'
⠋ Deploying web assets for 'dx/excshell/1'
deploy-static
✖ deploy-static skipped by hook 'dx/excshell/1'
New Extension Point(s) in Workspace 'Stage': 'dx/excshell/1'
Successful deployment 🏄
```
=> make hook messages consistent. this closes #470

bin/openwhisk-standalone-config/runtimes.json
1. https://hub.docker.com/r/adobeapiplatform/adobe-action-nodejs-v10/tags?page=1&ordering=last_updated
2. https://hub.docker.com/r/adobeapiplatform/adobe-action-nodejs-v12/tags?page=1&ordering=last_updated
3. https://hub.docker.com/r/adobeapiplatform/adobe-action-nodejs-v14/tags?page=1&ordering=last_updated
=> fix: update node runtimes.json

.gitignore, src/commands/app/delete/action.js, test/commands/app/delete/action.test.js
Bugfix for deleting actions e2e tests.
Generated e2e test files include `.test` extension.
Fixes #489
Manually
=> [ACNA-1369] aio app delete action doesn't delete the action e2e test

src/commands/app/run.js, test/commands/app/run.test.js
=> Clearer help text for apps with multiple extensions

README.md, package.json, src/commands/app/delete/extension.js
Fix app:delete:extensions help text.
=> fix: delete extensions text

src/commands/app/run.js, src/lib/run-dev.js, test/commands/app/build.test.js, test/commands/app/run.test.js, test/commands/lib/run-dev.test.js
Fixes #545
Variable should either be isLocal or isRemote throughout instead of negating the received value and passing it to another function.
[ACNA-1680](https://jira.corp.adobe.com/browse/ACNA-1680)
This is change for better code readability. It contains the simplification of variable naming conventions and their usage.
The unit test has been executed before raising PR with 100% code coverage and test case passing.
=> Fix: ACNA-1680 | not not not understandable code

src/commands/app/build.js, src/lib/run-dev.js, test/commands/app/build.test.js
There could be more html pages in a web-src, we need not limit our bundler to building /index.html alone.
=> feat: build all .html files, not just index. includes subdirs

src/commands/app/run.js
=> Command.load is now async, await it. This fixes #572

README.md, bin/run, package.json
=> chore: remove typescript dep, engineStrict, update bin/run

.github/workflows/node.js.yml
=> fix: update codecov from bash uploader to Github Action

src/commands/app/init.js
This is based on the master branch code, tested via the `@adobe/aio-cli-next` CLI.
Closes #581 
- npm test
-  manual test
=> fix: ACNA-1814 - `aio app init --standalone-app` should not ask for overwrite input

package.json
Bump inquirer checkbox table version to include new disabled option.
* Locally linked app plugin
* Locally ran `npm run test`
- [] My code follows the code style of this project.
=> chore: bump checkbox table version

src/TemplatesCommand.js, src/commands/app/init.js, test/commands/app/init.test.js
Fixes #600 
- npm test
- manual test via `aio plugins link .`
=> fix: ACNA-1839 - not properly showing templates only supported by my org

package.json
Bum to latest for app config lib. Required for response header support.
=> Bump app config lib version

package.json, test/commands/app/build.test.js, test/commands/app/create.test.js, test/commands/app/deploy.test.js, test/commands/app/geturl.test.js, test/commands/app/list/extension.test.js, test/commands/app/run.test.js, test/commands/app/test.test.js, test/commands/app/undeploy.test.js
=> fix: test failures under jest@29

package.json
=> bump aio-lib-web version

schema/deploy.yaml.schema.json, test/schema.test.js
Fixes #676 
Fixes https://github.com/adobe/aio-e2e-tests/issues/93
npm test
=> fix: deploy.yaml schema - workspaces key is not required

schema/config.schema.json
=> added validation rule for oauth_server_2_server

.github/workflows/release-branch.yml
=> Update release-branch.yml to node 14+16

bin/openwhisk-standalone-config/get-runtimes.js, bin/openwhisk-standalone-config/runtimes.json
=> Add support for aio app run --local w/ nodejs:18

test/__mocks__/@adobe/aio-lib-runtime.js
Add New Relic support to log forwarding
[Log forwarding New Relic support](https://github.com/adobe/aio-cli-plugin-app/issues/688)
[Add New Relic support to aio CLI](https://github.com/adobe/aio-cli-plugin-runtime/pull/311)
Log Forwarding currently supports Splunk and Azure Log Analytics. This PR adds support for New Relic.
Auto tests are included
=> CEXT-2009 Add New Relic support to aio CLI 

bin/openwhisk-standalone-config/get-runtimes.js, bin/openwhisk-standalone-config/runtimes.json
- aio app run --local should download the appropriate image in Docker
=> fix: update openwhisk standalone config for new node-20 runtime and tags

.github/workflows/daily.yml, .github/workflows/node.js.yml
Checks will fail on this PR because commits to master have broken node 14 support since Sept.
This does NOT resolve that issue, it simply and blindly steps forward into a 16+ world where things still work.
=> bump tests/checks from 14,16 to 16,18

.github/workflows/daily.yml, .github/workflows/node.js.yml, .github/workflows/on-push-publish-to-npm.yml, .github/workflows/prerelease.yml, .github/workflows/release-branch.yml, .github/workflows/version-bump-publish.yml, package.json
=> fix(breaking-change): update for nodes 18 and 20

test/jest.setup.js
This is to fix timeout issues under node-14 for the Github Action daily.yml
See https://github.com/adobe/aio-cli-plugin-app/actions/runs/6857278020
This PR is the test.
=> fix: increase jest timeout to 30s from 15s

src/commands/app/build.js
This should clean up an estimated overall 1/2 of our S3 deployments.
Note that S3 is only cleaned up on the next deploy of any namespace, so the full impact may take time to see.
[ACNA-2638](https://jira.corp.adobe.com/browse/ACNA-2638)
=> clean web.distProd on build

src/commands/app/config/get/log-forwarding.js, test/commands/app/config/get/log-forwarding.test.js
Closes https://github.com/adobe/aio-cli-plugin-app/issues/802
locally linked plugin, `npm run test`
=> fix: get log forwarding

src/commands/app/deploy.js, test/commands/app/deploy.test.js
=> Do not call console if we are not publishing, was forcing login

test/__fixtures__/pack/2.all.config.json, test/__fixtures__/pack/4.all.config.json, test/__fixtures__/pack/6.all.config.json
removes a few lingering places where the dreaded wskdebug showed up
=> Remove Whiskers aka Whisk Fixtures

src/lib/audit-logger.js
Update server used for audit logging.
- npm test
- manual tests
=> fix: ACNA-3375 - update cli to use Deploy Service for audit logging

package.json
This is a trivial change and relies on adobe/aio-lib-web#226 to be merged and released
⚠️ Note: ⚠️ CI will fail until the PR above is released.
=> fix(trivial): update aio-lib-web version explicitly to ^7.0.6
