- src/commands/cna/add-auth.js
This fixes a missing cna-scripts config error raised by oclif on every `aio` command.
Example of error: 
```
> aio
(node:87070) Error Plugin: @adobe/aio-cli-plugin-cna: Missing aio runtime config (set AIO_RUNTIME_XXX env vars)
module: @oclif/config@1.12.9
task: toCached
plugin: @adobe/aio-cli-plugin-cna
root: /Users/mraho/.aio-cna-repos/aio-cli-plugin-cna
See more details with DEBUG=*
(node:87070) Error Plugin: @adobe/aio-cli-plugin-cna: Missing aio runtime config (set AIO_RUNTIME_XXX env vars)
module: @oclif/config@1.12.9
task: toCached
plugin: @adobe/aio-cli-plugin-cna
root: /Users/mraho/.aio-cna-repos/aio-cli-plugin-cna
See more details with DEBUG=*
Adobe I/O Extensible CLI
VERSION
@adobe/aio-cli/1.5.1-dev.0 darwin-x64 node-v10.15.3
USAGE
$ aio [COMMAND]
...
```
npm run test
> Fix oclif cna scripts config loading error

- src/commands/cna/init.js
Small typo fix for the question `What folder do you want to use as your public directory?`, while asking for actions dir. It should be `What folder do you want to use as your actions directory?`.
https://github.com/adobe/aio-cli-plugin-cna/issues/39
> fix typo in init command

- README.md
- src/commands/cna/deploy.js
- test/commands/cna/deploy.test.js
Add a deploy only option to the deploy command.
This little change gives users the flexibility to use their own build command while still relying on our deployment process. Likewise a build only options was already provided.
> deploy only (no build) options

- src/commands/cna/test.js
- test/commands/cna/test.test.js
spinner was getting muxed with npm output, between pretest, test, and posttest
Removed redundant output
verbose flag means npm run is called with --silent=false
> remove spinner, --verbose means npm --silent=false

- src/templates/base/package.json
This makes @adobe/wskdebug a dev-dependency of the resultant project.
wskdebug requires a separate process so it cannot easily be wrapped into the cli tooling.
This also allows it to be targeted by .vscode tasks.
> add wskdebug dev-dependency

- src/commands/app/deploy.js
Users after a deploy don't have a record in the run log of what the app url is at. It was hidden under a verbose flag. This change makes it always print it out.
Bstter developer experience.
npm test
> fix: always print out the app url

- README.md
- src/commands/app/create.js
- src/commands/app/use.js
- src/lib/import.js
- test/commands/app/create.test.js
- test/commands/app/use.test.js
- test/commands/lib/import.test.js
- Add `app:use` command
- Add `app:create --import` flag
Import Adobe I/O Console downloadable config file.
npm test
> ACNA-613 - Add `app:use` and `app:create --import` command/flags

- src/lib/import.js
- test/__fixtures__/config.1.aio
- test/__fixtures__/config.2.json
- test/__fixtures__/config.3.json
- test/commands/lib/import.test.js
For the imported config, we need to validate certain keys to match requirements.
For the workspace name, project name, and org name, they have to match: ^[a-zA-Z0-9]+$
(one or more alphanumeric characters only)
Data validation
npm test
> fix: enforce validation rules on imported config

- src/commands/app/add/action.js
- src/commands/app/init.js
- test/commands/app/add/action.test.js
- test/commands/app/init.test.js
> fix add action command, fix auto merge in init

- src/commands/app/deploy.js
- src/commands/app/run.js
- src/commands/app/test.js
- src/lib/app-helper.js
- test/commands/app/deploy.test.js
- test/commands/app/test.test.js
- test/commands/lib/app-helper.test.js
Allows developers to include their own build process parts.
Scripts in package.json of running project will be executed in the following order:
- pre-app-build
- post-app-build
- pre-app-deploy
- post-app-deploy
- pre-app-run
- post-app-run
> run package.json scripts for [ pre | post ]-app-[ build | deploy | run ]

- src/commands/app/deploy.js
- src/commands/app/logs.js
- src/commands/app/run.js
- src/commands/app/undeploy.js
- src/lib/app-helper.js
- test/commands/app/logs.test.js
- test/commands/app/run.test.js
- test/commands/lib/app-helper.test.js
In some cases error thrown by app scripts and internally by Parcel are not `instanceof Error`.
This creates a problem when calling `this.error(notInstanceOfErrorButObject)` which will log `[Object object]`.
This is a workaround to make sure that error messages and stack are always printed
> Wrap errors to be printed correctly

- src/lib/import.js
- test/__fixtures__/config.6.orgid.aio
- test/__fixtures__/config.6.orgid.env
- test/__fixtures__/config.6.orgid.hjson
- test/__fixtures__/config.6.orgid.no.jwt.aio
- test/__fixtures__/config.6.orgid.no.jwt.env
- test/__fixtures__/config.6.orgid.no.jwt.hjson
- test/commands/lib/import.test.js
When importing the config, this pr ensures `ims_org_id` is copied to the `$ims.jwt` config.
The goal is to be compatible with required jwt configuration in https://github.com/adobe/aio-lib-core-ims-jwt/blob/master/src/ims-jwt.js#L21
> init --import: enrich jwt config with ims_org_id

- package.json
- src/commands/app/run.js
> Fix write certificate on first run command

- src/commands/app/deploy.js
- test/commands/app/deploy.test.js
**To be merged after https://github.com/adobe/aio-app-scripts/pull/81**
and after https://github.com/adobe/aio-app-scripts is released
fixes #91
> display action urls on deployment & run

- package.json
- src/commands/app/init.js
- test/commands/app/init.test.js
Addition of the console generator in app init. This requires user interaction in selecting the user's org, then project, then workspace -- to download the project config. The project config will then be imported and used.
To skip this user interaction, use the `--yes` or `--import` flag.
npm test
aio app init (should go through gen-console)
aio app init -y (skips gen-console)
aio app init --import config_file (skips gen_console)
> Use generator-aio-console in `app init`

- src/commands/app/init.js
- src/commands/app/use.js
- src/lib/app-helper.js
- test/commands/app/init.test.js
- test/commands/app/use.test.js
Fixes #228 
```
npm test
aio config rm \$ims && aio app init
aio config rm \$ims && aio app use
```
> fix: `aio app init` and `aio app use` failing if not logged in before (Error: IMS context '$cli' is not configured)

- src/lib/import.js
- test/__fixtures__/config.orgid.aio
- test/__fixtures__/config.orgid.no.jwt.aio
- test/__fixtures__/existing.merged.aio
- test/__fixtures__/valid.config.aio
Currently there is no way to know if the credentials belong to the workspace or not and what is the integration id.
This PR adds the credentials reference and id into the workspace config so that the credentials can be retrieved from the .env using that key
> feat: keep a reference to the credentials in the config

- package.json
- src/commands/app/deploy.js
- src/commands/app/run.js
- src/commands/app/undeploy.js
- src/lib/owlocal.js
- test/__mocks__/@adobe/aio-lib-web.js
- test/__mocks__/parcel-bundler.js
- test/commands/app/deploy.test.js
- test/commands/app/run.test.js
- test/commands/app/undeploy.test.js
- test/jest.setup.js
> rename app-scripts to aio-lib-web

- src/commands/app/init.js
- src/commands/app/use.js
- test/commands/app/init.test.js
- test/commands/app/use.test.js
deletes the console.json file in `app use` and `app init` when it was generated using the console generator
> delete console.json after generation in init and use

- src/lib/app-helper.js
- test/commands/lib/app-helper.test.js
Closes #315 
npm test
app hooks:
1. echo foo && echo bar
2. [[ "a" = "a" ]] && echo ok
3. echo it was okay > someFile.txt
4. cat package.json | jq .name
> fix: ACNA-949 - command chaining, and separators broken

- src/BaseCommand.js
- src/lib/owlocal.js
- src/lib/runDev.js
- test/commands/lib/ow-local.test.js
- test/commands/lib/runDev.test.js
- test/jest.setup.js
Two changes:
1. The OpenWhisk jar URL has been updated to include the [Windows Docker fix](https://github.com/apache/openwhisk/pull/5021): https://github.com/adobe/openwhisk/releases/tag/standalone-v1
2. The OpenWhisk jar is not downloaded into the aio-cli-plugin-app's `bin` folder anymore, but in the cli's `dataDir` folder as specified in the [oclif config](https://oclif.io/docs/config). On macOS, this location for `@adobe/aio-cli` is ` ~/.local/share/@adobe/aio-cli/openwhisk/openwhisk-standalone.jar`. This is so the .jar is not deleted on every app plugin update.
npm test
aio app run --local --verbose
> ACNA-942 - Windows: docker not found when running `aio app run --local --verbose` (openwhisk)

- src/lib/runDev.js
- test/commands/lib/runDev.test.js
This was broken from PR https://github.com/adobe/aio-cli-plugin-app/pull/320
Reverting this specific parcel-bunder entryPoint change.
Accessing https://localhost:9080/index.html works, but this is a break in the existing workflow.
This is a parcel-bundler issue: https://github.com/parcel-bundler/parcel/issues/1315 that has been fixed in parcel-bundler@2: https://github.com/parcel-bundler/parcel/pull/3996
We are using parcel-bundler@1.
npm test
aio app run
> fix: https://localhost:9080 404 Not Found in `aio app run`

- src/commands/app/run.js
- src/lib/app-helper.js
- src/lib/owlocal.js
- src/lib/runDev.js
- test/commands/lib/runDev.test.js
Openwhisk standalone logging to file can be set when `--verbose` is set for `aio app run`.
The log file will be truncated and written to in `dist/openwhisk-local.log.txt`. This log file location can be overridden via the `OW_LOCAL_LOG_FILE` environment variable as well.
This feature is to help with debugging.
#287 
npm test
aio app run --local --verbose
OW_LOCAL_LOG_FILE=mylog.txt aio app run --local --verbose
> fix: add logging to file for openwhisk-standalone.jar

- src/lib/config-loader.js
- test/commands/lib/config-loader.test.js
- test/jest.setup.js
Rename firefly app configuration key for `.aio` file to `app`
> fix: app config rename

- src/commands/app/build.js
- src/commands/app/deploy.js
- src/lib/config-loader.js
- test/commands/app/build.test.js
- test/commands/app/deploy.test.js
- test/jest.setup.js
Fixes #339 
- npm test
- add `build-actions` and/or `build-static` run scripts in `package.json` for your app, run `aio app build`
- add `deploy-actions` and/or `deploy-static` run scripts in `package.json` for your app, run `aio app deploy`
> ACNA-976 - feat: add new app event hooks for custom build scripts

- src/commands/app/build.js
- src/commands/app/deploy.js
- test/commands/app/deploy.test.js
1. `aio app build --help` (see new Description section of help text)
2. `aio app deploy --help` (see new Description section of help text)
3. `aio app deploy`
4. `aio app deploy --no-force-build`
5. `aio app build`
6. `aio app build --no-force-build`
7. npm test
> fix: revert `aio app deploy` flag `--force-build` to default to `true` (backwards compatibility)

- src/commands/app/init.js
- src/lib/import.js
- test/commands/lib/import.test.js
Always create .aio file with default app config for app init command.
Fixes #355 
When aio app is initialised with -y flag, .aio file was not created. 
Fixed this by writing .aio file with default app config at app init. When import or CLI login is used, .aio file will be merged with project config.
Default app config includes, name of actions, dist and web-src folder. This will help users to customise app if required.
unit tests, manual app init test
> fix: write default app config on app init

- src/lib/run-dev.js
- src/lib/run-local-runtime.js
- src/lib/vscode.js
- test/commands/lib/run-dev.test.js
- Fixes #362 
npm test
manual tests of `aio app run` (local and remote) with and without VS Code debugging
```
mkdir vscode-test
cd vscode-test
git clone https://github.com/adobe/generator-aio-app
cd generator-aio-app
git checkout vscode
npm i
cd ..
git clone https://github.com/adobe/aio-cli-plugin-app
cd aio-cli-plugin-app
git checkout vscode-gen
npm i
npm link ../generator-aio-app
aio plugins link .
cd ..
aio app run
```
> fix: use of generator-aio-app/add-vscode-config generator

- src/lib/config-loader.js
- test/commands/lib/config-loader.test.js
relates to https://github.com/adobe/aio-lib-web/pull/149 and https://github.com/adobe/aio-lib-core-tvm/pull/66/files
replaces https://github.com/adobe/aio-cli-plugin-app/pull/389/files
> Do not propagate default tvm url config

- src/commands/app/info.js
- test/commands/app/info.test.js
> added app info command, with tests

- src/lib/app-helper.js
- test/commands/lib/app-helper.test.js
Allows the user to override the parameters passed to the local openwhisk instance.
This can be used to override default configuration parameters.
*Example Usage*
If you have a function that requires more memory than the 512M default:
```bash
AIO_OW_JVM_ARGS="-Dwhisk.memory.max=1024M" aio app:run --local
```
Testing functions locally using the same resource configs as in the Adobe IO Runtime environment was not possible without modifying vendored code.
Tested locally using the `aio` cli.
> Allow overriding of local openwhisk jvm args

- bin/openwhisk-standalone-config/runtimes.json
- package.json
see https://hub.docker.com/r/adobeapiplatform/adobe-action-nodejs-v14/tags
Adds nodejs-14 runtime support for the local openwhisk.
1. Modify your runtime in your manifest.yml for node-14
2. Run it using `aio app run --local --verbose`
> feat: add nodejs-v14 support for local openwhisk

- src/lib/app-helper.js
- test/commands/lib/app-helper.test.js
Fixes #372 
Note that because of this fix, killing of `aio-run-detached` processes will not work on Windows, until this node bug is fixed.
npm test
> fix: ACNA-1026 - aio app test is failing on EBADF bad file descriptor (Windows only)

- src/lib/app-helper.js
- test/commands/lib/app-helper.test.js
- test/commands/lib/config-loader.test.js
- test/data-mocks/config-loader.js
> App helper tests + fix config loader once

- src/commands/app/build.js
- src/commands/app/deploy.js
- src/commands/app/undeploy.js
- test/commands/app/build.test.js
- test/commands/app/deploy.test.js
- test/commands/app/run.test.js
- test/commands/app/undeploy.test.js
This PR's base branch is `release-ext-reg`
unit tests all pass:
code coverage 100%:
> add tests for app: run, build, deploy, and undeploy (Extension Registry release)

- src/commands/app/get-url.js
- src/commands/app/logs.js
> Fix app get-urls and app logs

- src/commands/app/build.js
- test/__mocks__/ora.js
- test/commands/app/build.test.js
- if no actions match the -a flag, a message is displayed that shows this ( #444 )
- added aioLogger debug info describing what was built
- re-ordered some logic to prevent spinner/aioLogger output from becoming interlaced
- output message if building of action was skipped because of a 'build-actions' hook
#444
> inform user if no actions were built

- src/lib/app-helper.js
- test/commands/lib/app-helper.test.js
Helps in fixing [https://github.com/adobe/aio-apps-action/issues/10](https://github.com/adobe/aio-apps-action/issues/10)
For CI/CD deploy, the generated JWT token doesn't have scopes to get services details for a workspace. 
These details can be set as env var to avoid the API call, but while reading we need to convert them to JSON objects for further processing.
Following changes help support this. 
unit tests and manual test
> Fix CI/CD deploy error

- src/commands/app/deploy.js
- src/lib/app-helper.js
- src/lib/deploy-actions.js
- test/commands/app/deploy.test.js
- test/commands/lib/app-helper.test.js
- test/commands/lib/deploy-actions.test.js
Fixes #436
npm test
`aio app deploy`
`aio app run`
> fix: app run & deploy messages should differentiate between web action and non-web action URLs

- src/commands/app/init.js
> Create new yeoman env to workaround issue with conflicter

- src/commands/app/init.js
- test/commands/app/init.test.js
We have some dialog input that is not easily automated for e2e/integration tests.  This pr adds a --extension:String flag to allow easy testing.
currently --extension is expected to be one ( or more ) of [`dx/asset-compute/worker/1`, `dx/excshell/1`, `application`]
https://jira.corp.adobe.com/browse/ACNA-1271
with tests
> parameterize extensions

- package.json
- src/lib/actions-watcher.js
- test/commands/lib/actions-watcher.test.js
Changing non-action files should not trigger `buildAndDeploy` process but instead, it should notify the user that those changes require an app restart in order to be deployed.
Skip deploying when the changed file path is not a valid action path. 
Updated `chokidar` to latest, changelog https://github.com/paulmillr/chokidar/compare/3.4.2...3.5.2
https://github.com/adobe/aio-cli-plugin-app/issues/474
https://github.com/adobe/aio-lib-runtime/pull/75#issuecomment-945409660
Manually
> [ACNA-1357] Optimize deploy to skip build & deploy.

- src/commands/app/config/get/log-forwarding.js
- src/commands/app/config/set/log-forwarding.js
- src/lib/log-forwarding.js
- test/commands/app/config/get/log-forwarding.test.js
- test/commands/app/config/set/log-forwarding.test.js
- Fix for: Log Forwarding secrets are not saved in the project's `.env` file.
- Improved log forwarding message in case local config is absent
Manual and auto tests.
> Fixed: log-forwarding secret settings are not saved

- src/commands/app/deploy.js
- test/commands/app/deploy.test.js
- spinner.info instead of spinner.error
- chalk.dim instead of chalk.green
- only display **Log forwarding is not updated: no configuration is provided** if `--verbose`
- adds sanity check for missing .aio file or properties, no deeper processing is done
- `aio app deploy` (not verbose)
- `aio app deploy --verbose`
> log-forwarding config: downplay spinner messaging

- src/commands/app/init.js
The prompt for developers' terms should also include a nice message asking them to accept the terms.
> fix: added a friendly message asking for terms acceptance.

- README.md
- package.json
Modified README to change file extensions in links to source code from `.ts` to `.js`.
This change is required so that links to source files will work. 
Manually tested via personal fork of repository.
> Fix links to source code in README

- src/lib/defaults.js
- src/lib/import.js
- test/__fixtures__/existing.merged.env
- test/__fixtures__/valid.config.env
Remove adding runtime apihost during environment config generation.
- [] I have added tests to cover my changes.
> remove adding runtime apihost to env config

- src/lib/defaults.js
- src/lib/import.js
- test/__fixtures__/existing.merged.env
- test/__fixtures__/valid.config.env
This reverts commit cb1b5c05d4c9afaa7ee57a1b96c5af26c31db4b1.
`AIO_runtime_apihost` is read by `wskdebug` to get openwhisk server runtime docker image data, so it is a necessary part of the environment configuration for a base app if we want to support local debugging.
https://github.com/adobe/aio-cli-plugin-app/issues/541
Test locally. 
- [] My change requires a change to the documentation.
> Revert "fix: remove adding runtime apihost to env config (#535)"

- src/lib/build-actions.js
- src/lib/run-dev.js
- test/commands/app/run.test.js
- test/commands/lib/build-actions.test.js
- test/commands/lib/run-dev.test.js
Fixes #542 
(see issue for use case)
In a nutshell, we will always force deploy actions on every `aio app run` (doesn't matter if there are no code changes).
npm test
manual test
> fix: force build on every aio app run (for switching from remote and local contexts)

- .github/workflows/node.js.yml
- package.json
This pr bumps node support to LTS versions and drops support for 12 which is EOL
Minor version choices are to ensure we get node: namespace supporting versions of node. 
CI
note that the node-12 tests will not finish since it has been removed in the Github Action CI script
> breaking: remove node-12 support

- bin/openwhisk-standalone-config/get-runtimes.js
- bin/openwhisk-standalone-config/runtimes.json
- package.json
> fix: ACNA-1375 - updater for runtimes.json for aio app run --local

- src/commands/app/add/action.js
- src/commands/app/add/ci.js
- src/commands/app/add/event.js
- src/commands/app/add/extension.js
- src/commands/app/add/web-assets.js
- src/commands/app/delete/ci.js
- src/commands/app/init.js
- src/lib/vscode.js
- test/commands/app/add/action.test.js
- test/commands/app/add/ci.test.js
- test/commands/app/add/event.test.js
- test/commands/app/add/extension.test.js
- test/commands/app/add/web-assets.test.js
- test/commands/app/delete/ci.test.js
- test/commands/app/init.test.js
Fixed option `skipInstall` for yeoman generators used for scaffolding App Builder Apps
This PR aims to fix skipInstall options issue with yeoman generators. There is a slight change to how to use this option to make it work.
https://github.com/adobe/aio-cli-plugin-app/issues/554
npm dependencies seem to be installed twice once after the base-app gets generated and at the end before the app initialization is over
Expected behaviour: npm dependencies should only be installed at the end of the project initialization once the package.json deps are all defined.
Locally tested by creating an app - npm packages are now installed only at the end. Generators skip installing packages. All units tests run successful locally.
Generators skipping installing packages:
> fix: ACNA-1687 | fix option skipInstall for generators

- src/commands/app/init.js
- test/commands/app/init.test.js
This is based on the master branch code, tested via the `@adobe/aio-cli-next` CLI.
The fix is passing a flag to the `templates` plugin to not process the template install.yml config, which requires a user login.
Closes #582 
- npm test
- manual test
> fix: ACNA-1812 - `aio app init --no-login --extension dx/excshell/1` should not error

- src/commands/app/build.js
- src/commands/app/deploy.js
- src/commands/app/run.js
- src/commands/app/undeploy.js
- test/commands/app/build.test.js
- test/commands/app/deploy.test.js
- test/commands/app/run.test.js
- test/commands/app/undeploy.test.js
There have been deprecated flags in the app plugin. e.g. `--skip-???` that already have other flag equivalents. 
Removal of these flags is a `breaking change`, thus a `major version bump` to v10.
For the `app deploy` command I didn't change `skip-deploy` to `deploy` with `allowNo:true` because it didn't make sense at all, and removed any tests for `skip-deploy`.
manual testing of app:
- deploy 
- undeploy
- build
-  run
> fix: ACNA-1807 - remove deprecated flags in the commands

- src/commands/app/deploy.js
- test/commands/app/deploy.test.js
fixes #587 
1. `npm test`
2. `aio plugins link .` (in the app plugin folder of this PR branch)
1. ` aio app init my-app-1 --no-login --yes --standalone-app`
2. `cd my-app`
3. `aio app deploy`
1. `aio app init my-app-2 --no-login --yes --extension dx/excshell/1`
2. `cd my-app`
3. `aio app deploy --no-publish`
> fix: ACNA-1817 - error when trying to deploy an app created with `aio app init --no-login`

- src/commands/app/init.js
If the user does not select any templates, initialize a standalone application. 
closes https://github.com/adobe/aio-cli-plugin-app/issues/591
This fixes a workflow that results in an un-deployable App Builder application.
* Locally linked app plugin 
* Locally ran `npm run test`
> fix: init standalone-app if no templates are selected

- src/commands/app/add/action.js
- src/commands/app/add/service.js
- src/commands/app/delete/service.js
- test/commands/app/add/action.test.js
Closes #592 
- npm test
- manual test (aio app add action, aio app add service, aio app delete service)
> fix: ACNA-1822 - `aio app add action` fails with console error without local .aio file

- src/commands/app/deploy.js
- test/commands/app/deploy.test.js
Closes #598 
- npm test
-  manual test
> fix: deploy error (Production workspace): Error: Cannot read properties of undefined (reading 'getProject')

- src/commands/app/deploy.js
- test/commands/app/deploy.test.js
Using the `--action` flag sets `--publish` to false, therefore we should allow `--no-publish` when using `--action`. 
Closes https://github.com/adobe/aio-cli-plugin-app/issues/607
Confusing flags
Locally linked app plugin and `npm run test`
> fix: allow --no-publish with --action

- src/lib/run-dev.js
Closes #609
1. npm test
2. manual test (link local app plugin, set serve-static hook, then `aio app run`)
> fix: ACNA-1786 - serve-static hook error

- test/commands/app/info.test.js
- test/commands/app/test.test.js
> fix: ACNA-2092 - unit-test failures: aio-lib-ims-oauth 5.1.0

- src/lib/app-helper.js
- test/commands/app/deploy.test.js
- test/commands/lib/app-helper.test.js
- test/commands/lib/deploy-actions.test.js
This fixes the missing deployed action list output, e.g.
from
```
➜  aio app deploy
✔ Deployed 2 action(s) for 'application'
no frontend, skipping frontend deploy 'application'
Your deployed actions:
[MISSING OUTPUT]
```
to
```
➜  aio app deploy
✔ Deployed 2 action(s) for 'application'
Your deployed actions:
web actions:
-> https://<ns>.adobeioruntime.net/api/v1/web/dx-excshell-1/generic
non-web actions:
-> dx-excshell-1/__secured_generic
```
unit tests + manual e2e testing
> fix: output deployed action list

- jsconfig.json
- package.json
- test/commands/lib/log-poller.test.js
- test/commands/lib/vscode.test.js
- test/jest.setup.js
Closes #631
- Removes usage of the fake filesystem in tests because of incompatibility with fs-extra@11.x (see #631)
- npm test
> removed fake file system usage, update fs-extra to v11

- src/TemplatesCommand.js
- src/commands/app/deploy.js
- src/lib/deploy-actions.js
- test/commands/app/deploy.test.js
- test/commands/lib/deploy-actions.test.js
> Hook errors#665

- src/commands/app/install.js
- src/commands/app/pack.js
- src/commands/app/test.js
- test/commands/app/install.test.js
- test/commands/app/pack.test.js
- add `npm install` step to `aio app install` (if not `aio app test` will fail)
- `aio app pack` will not include the output zip (if it exists in the project)
- cleaned up info output by using ora spinner
- updated tests and coverage
- npm test
- manual tests
> fix: aio app pack, aio app install output cleanup, fixes

- src/BaseCommand.js
- src/commands/app/install.js
- src/commands/app/pack.js
1. fixed app install unzip concurrency issue
- npm test
- manual tests
> fix: add pre-release warning text, hide pre-release commands from help listing

- src/TemplatesCommand.js
Making it more clear that users can skip template selection during `aio app init`
https://github.com/adobe/aio-cli-plugin-app/issues/683
Users are asking for help at this step in slack
tested plugin locally with and without template selection
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x] I have read the **CONTRIBUTING** document.
- [ x] All new and existing tests passed.
> Improve message to users around template selection

- src/commands/app/deploy.js
Flag is passed to pre-deploy-event-reg and post-deploy-event-reg hooks to indicate if remote event registrations should be deleted if they are not present in appConfig
ACNA-1998
> pre/post-deploy-event-reg receives force boolean --force-events

- src/commands/app/pack.js
- test/commands/app/pack.test.js
If the user has the api-mesh plugin installed and runs `aio app pack` on a project without an api-mesh config, packing will fail with a not found error. This PR proposes ignoring these errors and continuing to pack
Closes https://github.com/adobe/aio-cli-plugin-app/issues/699
So `aio app pack` works with all plugins installed
Locally linked plugin, `npm run test`
> fix: handle mesh config 404 error

- src/commands/app/pack.js
- test/__fixtures__/pack/2.deploy.yaml
This PR removes application developer details from the `meshConfig` portion of `deploy.yaml`, generated when the developer runs `aio app pack`
The `api-mesh get` command returns information about the application developer, which can be omitted from `deploy.yaml` since a new mesh config can be created with only the data in the `meshConfig` key
```
{
"lastUpdated": "2023-08-29T16:20:01.202Z",
"meshConfig": {
"sources": [
{
"name": "Commerce",
"handler": {
"graphql": {
"endpoint": "https://venia.magento.com/graphql/"
}
}
}
]
},
"meshId": "ee487aab-e92e-4035-a757-e18858ef7a92",
"lastUpdatedBy": {
"firstName": "Michael",
"lastName": "Goberling",
"userEmail": "mgoberling@adobe.com",
"userId": "4E561E5C62E3F21E0A494122@AdobeID",
"displayName": "Michael%20Goberling"
},
"meshStatus": "success", …
```
> remove isv dev details from mesh config while packing

- package.json
- src/commands/app/add/event.js
This fix adds event registrations in the app config file under the desired extension 
Use event-config-path to add event registrations in the config file
https://github.com/adobe/generator-app-common-lib/pull/48
> Call events template with additional option events-config-path

- package.json
- src/commands/app/pack.js
- test/commands/app/pack.test.js
Currently the files to be packed are defined by `npm pack --dry-run --json` and exclusions are defined by the `.gitignore` file. However, if the app folder does not have `.gitignore`, certain sensitive files may still be included. This PR will exclude these files no matter what.
These files are excluded from being packed:
1. any "hidden" file by convention (file that starts with a '.')
2. any junk file as defined by https://www.npmjs.com/package/junk
npm test
> fix: ACNA-2561 - app pack command should exclude hidden files

- src/commands/app/pack.js
- test/commands/app/pack.test.js
These files have been moved:
1. `app-package` artifacts folder has been moved to `dist/app-package`
2. the default output `app.zip` has been moved to `dist/app.zip`.
This has been added:
1. all extension `dist` folders are excluded from the pack
2. the `dist` folder itself is excluded from the pack (just in case the .gitignore value is not there)
3. the `dist/app-package` folder will be deleted after the pack
1. npm test
2. `aio app pack` on an App Builder project
> fix: ACNA-2562 - artifacts and zip output should be in a .gitignored dist folder

- src/commands/app/install.js
- test/commands/app/install.test.js
Sometimes users want to skip running tests when running `aio app install`
This PR proposes adding `--tests` and `--no-tests` flags for users 
Locally linked plugin, `npm run test`
> feat: add tests flag to install command

- src/commands/app/install.js
- src/commands/app/pack.js
- test/BaseCommand.test.js
- test/commands/app/install.test.js
- test/commands/app/pack.test.js
> fix: app pack and app install help was hidden in the README text

- README.md
- package.json
closes #759
1. rm -rf node_modules
2. npm i
3. npm test
4. npm run prepack
5. Inspect README.md for `See code:` links (should point to the `.js` file)
> fix: ACNA-2800 - code links in README point to a .ts file

- package.json
- src/commands/app/deploy.js
- test/commands/app/deploy.test.js
Skip publish attempt if user force deploys a production prod app (Since console returns an error) 
Closes https://github.com/adobe/aio-cli-plugin-app/issues/761
`npm run test`, locally linked plugin
> fix: misleading publish errors

- src/commands/app/pack.js
- test/__fixtures__/pack/3.api-mesh.get.json
- test/commands/app/pack.test.js
Start using the `--json` flag when getting api-mesh during `aio app pack` and throw any resulting stderr
Closes https://github.com/adobe/aio-cli-plugin-app/issues/773
Locally linked plugin, `npm run test`
> fix: pack throws getting api-mesh

- src/commands/app/init.js
- test/commands/app/init.test.js
Add an optional `--linter` flag 
Depends on: https://github.com/adobe/generator-aio-app/pull/247
Closes https://github.com/adobe/aio-cli-plugin-app/issues/738
`npm run test`, locally linked plugin
> feat: --linter flag

- src/commands/app/use.js
> Add -m flag for --merge in app use

- src/lib/app-helper.js
- test/commands/lib/app-helper.test.js
`waitForOpenWhiskReadiness` timeout now include most recent error in throw, e.g. `FetchError: request to http://localhost:3233/api/v1 failed, reason: connect ECONNREFUSED ::1:3233`
Subsequent OpenWhisk local runs keep timing out after initial runs were working. I had to debug in this way to understand why.
OT: createFetch cannot access local port suggesting OW is not running, but it is and my browser can access. Definitely some unrelated bug.
- unit test
- monkeypatch manual test:
```sh
Error: local openwhisk stack startup timed out after 60000ms due to FetchError: request to http://localhost:3233/api/v1 failed, reason: connect ECONNREFUSED ::1:3233
at Object.error (/Users/hgpa/hgpa/git/git.corp.adobe.com/wcms/seotech/node_modules/@adobe/aio-cli-plugin-app/node_modules/@oclif/core/lib/erro …
```
> Log most recent error when OpenWhisk readiness times out

- .github/workflows/node.js.yml
~_Note: Using this pr as a test bed for the branch that does not require the CODECOV_TOKEN to see if node ci still runs_~ it works 🥳 
Inherit secrets in the Node.JS CI workflow so we can upload coverage using the codecov@v4 action in the re-usable workflow.
> feat: inherit secrets for node.js CI workflow

- src/commands/app/init.js
- test/commands/app/init.test.js
fixes #792 
- npm test
- manual test after local link of the plugin
> fix: incorrect logic for flag --confirm-new-workspace in command aio app init

- package.json
- src/commands/app/init.js
- test/commands/app/init.test.js
⚠️ **Note:** needs https://github.com/adobe/aio-cli-plugin-app-dev installed for debugging - this new plugin should be a core plugin in the aio-cli
- npm test
- aio app init MyApp, then running the debugger on an action (works on an app with frontend/extension, `--standalone-app` has this [issue](https://github.com/adobe/aio-cli-plugin-app-dev/issues/22))
> feat: run add-vscode-config generator on app init (retooled local debugging)

- src/commands/app/init.js
- test/commands/app/init.test.js
> record quickstart usage to telemetry, w/tests

- src/commands/app/deploy.js
- test/commands/app/deploy.test.js
fixes #805
Cleaned up the initialization of libConsoleCLI in the Deploy command. It is unnecessary to initialize it in the command's `run` method, since in BaseCommand, the getter function is already in a singleton pattern and the instance is lazy loaded. 
Any functions that need this instance can just call it directly, and it does not have to be passed down from the `run()` command, where the initialization is dependent on potentially faulty logic (that has been removed).
- npm test
- manual testing
- `aio app init MyApp` (create an exc-shell extension app)
- `aio app use` (choose Production workspace)
- `aio app deploy -a your_action_to_deploy`
> fix: ACNA-3024 - deploy single action error

- package.json
- src/commands/app/build.js
- src/commands/app/deploy.js
- src/commands/app/run.js
- src/lib/actions-watcher.js
- src/lib/run-dev.js
- test/commands/app/build.test.js
- test/commands/app/deploy.test.js
- test/commands/lib/run-dev.test.js
This changes the default for flag --force-build to false
RuntimeLib will include additional checks to not build actions it has already built, and not deploy actions already deployed.  In order for users to see these benefits, the defaults are to use the optimized workflow and reduce time to build/deploy/run
If an action has changed, it will be built during app build/deploy/run
If an action has changed ( or action inputs including from $env or action descriptors ) it will be deployed during app deploy/run
> Optimize build and deploy

- .github/workflows/on-push-publish-to-npm.yml
Add the parameter to the github action, so that on publish, the scope is always public.
If not, we would have to update it in npm manually from private to public, and that requires someone with npm org admin privileges.
This is not a problem if it's already public - but generally when you first publish it (especially for a new repo).
Why this PR? Since we often copy workflows from existing repos, I am adding it here to the 2 most popular repos so this issue won't happen.
> fix: update on-push-publish-to-npm.yml

- src/lib/audit-logger.js
- test/BaseCommand.test.js
- test/__mocks__/@adobe/aio-lib-env.js
- test/commands/lib/audit-logger.test.js
This will clean up master, currently running without env=stage will call a non-existent service.
> Unblock dev

- src/commands/app/deploy.js
- src/lib/app-helper.js
- test/commands/lib/app-helper.test.js
> do not force login if deploy with --no-publish

- src/commands/app/build.js
- src/commands/app/deploy.js
- test/commands/app/build.test.js
- test/commands/app/deploy.test.js
This changes the default flags, but no implementation.
Effectively the default behavior will be:
- `aio app build --force-build`
- `aio app deploy --force-build`
> Force true

- src/commands/app/deploy.js
- test/commands/app/deploy.test.js
- local link the plugin
- try to deploy with `--verbose`, it should error in the audit log api (there is a bug/service issue currently), and show the exception message
> fix: deploy - output the error from the audit log api if `--verbose` is set

- src/commands/app/clean.js
- test/commands/app/clean.test.js
This pull request renames the command from CleanBuild to Clean to simplify the terminology.
Renames the command class and references in the source and test files.
Updates descriptions and exports accordingly.
> clean-build becomes just clean

- src/commands/app/undeploy.js
- test/commands/app/undeploy.test.js
closes #830
- local link this app plugin PR branch
- `aio app deploy` then
- `aio app undeploy` (should run `aio app clean`)
- `aio app deploy` after should not error (the usual workaround was to `rm -rf dist`)
> fix: ACNA-3828 - `aio app undeploy` should remove the build cache

- src/commands/app/deploy.js
- src/lib/app-helper.js
- src/lib/auth-helper.js
- test/commands/app/config/get/log-forwarding.test.js
- test/commands/app/deploy.test.js
- test/commands/lib/app-helper.test.js
closes #871 
- npm test
- `aio app clean && aio app deploy` on a project with app plugin linked master branch code - note the action urls printed out to the log
> fix: ACNA-3864 - action URLs are output with deploy service URL

- src/lib/auth-helper.js
- test/commands/app/config/get/log-forwarding.test.js
- test/commands/lib/auth-helper.test.js
Fixes #872 
- aio app deploy on Stage and Prod, by only changing AIO_CLI_ENV
- used linked app plugin for Deploy Service
> fix: ACNA-3928 - AIO_CLI_ENV not respected for deploy service URL

- src/commands/app/deploy.js
- src/commands/app/undeploy.js
- src/lib/auth-helper.js
- test/commands/app/deploy.test.js
- test/commands/app/undeploy.test.js
- test/commands/lib/auth-helper.test.js
https://jira.corp.adobe.com/browse/ACNA-3953
Activity logs for extensions were not showing up:
1. start of deploy
2. start of undeploy
3. web assets deployed
4. web assets undeployed
For standalone apps, the activity logs were fine.
- `aio app deploy` for a project with an extension, e.g Experience Cloud Shell extension
- `aio app deploy` for a standalone project (--stand-alone)
- `aio app deploy` with a technical account credential
- All relevant logs including the missing ones should show up in the project's Activity Log
> fix: ACNA-3953 - activity logs not showing for extensions

- package.json
The version has an important bug fix.
This depends on https://github.com/adobe/aio-lib-runtime/pull/215 being merged and released as 7.1.3, thus the CI checks will fail until then.
> fix: update aio-lib-runtime version to explicit 7.1.3
